services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: skymailr
      POSTGRES_PASSWORD: skymailr
      POSTGRES_DB: skymailr
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn -c gunicorn.conf.py config.wsgi:application
    env_file: .env
    environment:
      DATABASE_URL: postgres://skymailr:skymailr@db:5432/skymailr
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: config.settings.development
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config worker -l info
    env_file: .env
    environment:
      DATABASE_URL: postgres://skymailr:skymailr@db:5432/skymailr
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: config.settings.development
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A config beat -l info
    env_file: .env
    environment:
      DATABASE_URL: postgres://skymailr:skymailr@db:5432/skymailr
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: config.settings.development
    depends_on:
      - db
      - redis

volumes:
  pgdata:
