# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('transactional', 'Transactional'), ('lifecycle', 'Lifecycle'), ('marketing', 'Marketing'), ('system', 'System')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sends_total', models.PositiveIntegerField(default=0)),
                ('delivered_total', models.PositiveIntegerField(default=0)),
                ('opens_total', models.PositiveIntegerField(default=0)),
                ('clicks_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('created_by_type', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('llm', 'LLM')], default='system', max_length=16)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('llm_generated', 'LLM generated'), ('llm_revised', 'LLM revised'), ('seeded', 'Seeded')], default='manual', max_length=32)),
                ('subject_template', models.TextField()),
                ('preview_text_template', models.TextField(blank=True)),
                ('html_template', models.TextField()),
                ('text_template', models.TextField(blank=True)),
                ('subject_variants', models.JSONField(blank=True, default=list, help_text='Optional A/B subject line variants (list of template strings).')),
                ('design_schema', models.JSONField(blank=True, default=dict)),
                ('compliance_flags', models.JSONField(blank=True, default=dict)),
                ('locked_sections', models.JSONField(blank=True, default=list, help_text='Sections LLM must not edit: header, body, cta, footer, compliance.')),
                ('changelog', models.TextField(blank=True)),
                ('llm_prompt', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=128)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('is_current_approved', models.BooleanField(default=False, help_text='The single version used for sending (approved, active).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_template_versions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['template', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='LLMGenerationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('prompt', models.TextField()),
                ('model', models.CharField(max_length=128)),
                ('temperature', models.FloatField(default=0.4)),
                ('raw_output', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(blank=True, default=dict)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(default='pending', max_length=32)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_records', to='email_templates.emailtemplateversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_generations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_events', to='email_templates.emailtemplateversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRenderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('subject_rendered', models.TextField(blank=True)),
                ('html_rendered', models.TextField(blank=True)),
                ('text_rendered', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_logs', to='email_templates.emailtemplateversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uniq_template_key_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='uniq_version_number_per_template'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_approved', True)), fields=('template',), name='uniq_current_approved_per_template'),
        ),
        migrations.AddConstraint(
            model_name='templatevariable',
            constraint=models.UniqueConstraint(fields=('template', 'name'), name='uniq_var_per_template'),
        ),
    ]
