# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_templates', '0001_initial'),
        ('skymailr_workflows', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, max_length=64)),
                ('raw_body', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_app', models.CharField(db_index=True, max_length=64)),
                ('message_type', models.CharField(choices=[('transactional', 'Transactional'), ('lifecycle', 'Lifecycle'), ('marketing', 'Marketing'), ('system', 'System')], max_length=32)),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('cc', models.JSONField(blank=True, default=list)),
                ('bcc', models.JSONField(blank=True, default=list)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject_rendered', models.TextField(blank=True)),
                ('html_rendered', models.TextField(blank=True)),
                ('text_rendered', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Critical transactional'), (1, 'Normal transactional'), (2, 'Lifecycle'), (3, 'Marketing')], default=1)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('send_after', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('rendered', 'Rendered'), ('sending', 'Sending'), ('sent', 'Sent'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=32)),
                ('provider_name', models.CharField(blank=True, max_length=64)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.senderprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='email_templates.emailtemplate')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='email_templates.emailtemplateversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='tenants.tenant')),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='skymailr_workflows.workflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('provider_name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=128)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='skymailr_messages.outboundmessage')),
            ],
            options={
                'ordering': ['message', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('rendered', 'Rendered'), ('sent', 'Sent'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='skymailr_messages.outboundmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKeyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='tenants.tenant')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_record', to='skymailr_messages.outboundmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('feedback_type', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='tenants.tenant')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skymailr_messages.outboundmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BounceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('bounce_type', models.CharField(default='hard', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='tenants.tenant')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skymailr_messages.outboundmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='skymailr_me_tenant__0c5445_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['tenant', 'to_email', 'status'], name='skymailr_me_tenant__14cb3f_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='skymailr_me_status_dcfa28_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboundattempt',
            constraint=models.UniqueConstraint(fields=('message', 'attempt_number'), name='uniq_attempt_per_message'),
        ),
        migrations.AddIndex(
            model_name='messageevent',
            index=models.Index(fields=['message', 'event_type', 'created_at'], name='skymailr_me_message_29c316_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencykeyrecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'key_hash'), name='uniq_idempotency_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='bouncerecord',
            index=models.Index(fields=['tenant', 'email'], name='skymailr_me_tenant__318e75_idx'),
        ),
    ]
