# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=32)),
                ('default_sender_name', models.CharField(blank=True, max_length=200)),
                ('default_sender_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('sending_domain', models.CharField(blank=True, help_text='Expected outbound domain / subdomain metadata for DNS alignment.', max_length=255)),
                ('transactional_enabled', models.BooleanField(default=True)),
                ('marketing_enabled', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, help_text='Soft cap; enforced in dispatcher.')),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('llm_defaults', models.JSONField(blank=True, default=dict, help_text='Keys: default_model, temperature, tone_profile, brand_voice_notes')),
                ('compliance_footer_html', models.TextField(blank=True, help_text='Appended to marketing HTML when tenant requires legal block.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key_hash', models.CharField(editable=False, max_length=128, unique=True)),
                ('prefix', models.CharField(default='sk_live_', max_length=16)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant API key',
                'verbose_name_plural': 'Tenant API keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('dkim_status', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='SenderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('transactional', 'Transactional'), ('marketing', 'Marketing / lifecycle')], max_length=32)),
                ('from_name', models.CharField(max_length=200)),
                ('from_email', models.EmailField(max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_profiles', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'category', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'category'), name='unique_default_sender_per_tenant_category')],
            },
        ),
    ]
