# Generated by Django 6.0.4 on 2026-04-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='senderprofile',
            name='unique_default_sender_per_tenant_category',
        ),
    ]
