# Generated by Django 6.0.4 on 2026-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenantdomain_postal_verification_bridge_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdomain',
            name='mx_targets',
            field=models.JSONField(blank=True, default=list, help_text='Inbound MX hostnames from Postal (priority 10 in UI); informational DNS rows.'),
        ),
    ]
