# Generated by Django 5.2.13 on 2026-04-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenantdomainsendingpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_risk_eval_at',
            field=models.DateTimeField(blank=True, help_text='Last automated risk evaluation (e.g. after webhook).', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_risk_review_at',
            field=models.DateTimeField(blank=True, help_text='When an operator last acknowledged risk on this tenant.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_daily_sends_override',
            field=models.PositiveIntegerField(blank=True, help_text='Optional per-tenant daily cap (future dispatcher use); null = plan/default only.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='operator_risk_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='risk_metrics_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0–100 heuristic from recent bounces/complaints/volume (operator visibility).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sending_pause_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sending_pause_scope',
            field=models.CharField(blank=True, choices=[('marketing_lifecycle', 'Marketing & lifecycle only'), ('non_critical', 'All except system (critical)')], default='marketing_lifecycle', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sending_pause_source',
            field=models.CharField(blank=True, choices=[('manual', 'Operator'), ('auto', 'Automated risk')], help_text='Who set the current pause (null when not paused).', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sending_paused',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
