# Generated by Django 5.1.15 on 2026-04-22 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppressionRemovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_suppression_id', models.UUIDField(db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('reason', models.CharField(max_length=32)),
                ('metadata_snapshot', models.JSONField(blank=True, default=dict)),
                ('removed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-removed_at'],
            },
        ),
    ]
