# Generated by Django 6.0.4 on 2026-04-14 13:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_templates', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSendWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('weekdays', models.JSONField(default=list, help_text='0=Monday .. 6=Sunday')),
                ('start_hour_local', models.PositiveSmallIntegerField(default=9)),
                ('end_hour_local', models.PositiveSmallIntegerField(default=17)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_windows', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('external_user_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenants.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='skymailr_workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('send_template', 'Send template'), ('wait_duration', 'Wait duration'), ('conditional_branch', 'Conditional branch'), ('set_tag', 'Set tag'), ('unsubscribe_if_condition', 'Unsubscribe if condition'), ('end', 'End')], max_length=64)),
                ('template_key', models.CharField(blank=True, help_text='Fallback lookup if template FK not set.', max_length=128)),
                ('wait_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('tag_value', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='skymailr_workflows.workflowstep')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_templates.emailtemplate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='skymailr_workflows.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=32)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='skymailr_workflows.workflowenrollment')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skymailr_workflows.workflowstep')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='skymailr_workflows.workflowexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skymailr_workflows.workflowstep')),
            ],
            options={
                'ordering': ['run_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uniq_workflow_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='workflowenrollment',
            index=models.Index(fields=['tenant', 'workflow', 'recipient_email'], name='skymailr_wo_tenant__096f6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='uniq_step_order_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['status', 'next_run_at'], name='skymailr_wo_status_1ee5ef_idx'),
        ),
    ]
